"#MeToo" Me Too
===============
Shlomi Fish <shlomif@cpan.org>
:Date: 2019-10-31
:Revision: $Id$

[id="intro"]
Introduction
------------

The premise of this essay / braindump / humour piece is that there is a very
strong correlation between competence and ability (see https://en.wikipedia.org/wiki/From_each_according_to_his_ability%2c_to_each_according_to_his_needs[Karl Marx's misled quote] to sexiness / attractiveness / "hot"ness. This may in turn
correspond to https://en.wikipedia.org/wiki/Fitness_(biology)[human biological fitness], which does not fully correspond to the so-called https://en.wikipedia.org/wiki/Physical_fitness[Physical fitness] .

We are planning to collect as many sexualised and even "sexist" jokes about both females and males from https://www.shlomifish.org/humour/fortunes/[our arsenal] to evoke a strong https://en.wikipedia.org/wiki/Me_Too_movement["Me Too"] reaction which we will then take to our advantage. https://en.wikipedia.org/wiki/Bring_It_On_(film)[Bring It On!]

We will show that these people (or non people) are noble, capable, admired,
and revered, *because* they are so sexually attractive, not despite it.

[id="knowing-John-Galt"]
John Galt
---------

[quote, Shlomi Fish, 'Summer Glau Facts']
___
By the time Chuck Norris found out who John Galt is, Summer Glau already had sex with him.
__

*Midrash*: part of the reason why I found it funny is because the ancient Hebrew
verb https://en.wiktionary.org/wiki/%D7%99%D7%93%D7%A2[Yada`] had both meanings, as well as a meaning of "to create/conceive something with pleasure" and possibly other meanings of the geek jargon verb http://www.catb.org/jargon/html/H/hack.html["hack"]. Also see https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/#hacking-heroism[hacking and heroism].

== No concented sexual behaviour is unacceptable

=== Introduction

All sexual behaviour is perfectly acceptable and respectful, including:

* *Selling* sexual services for money -
*http://en.wikipedia.org/wiki/Prostitution[Prostitution]*.
* Starring in hardcore
*http://en.wikipedia.org/wiki/Pornography[pornographic]* films.
* Being a ``slut'' or a ``bimbo'': having casual sex with more than one
sex partner.
* Being polyamorous - having more than one stable sexual relationship at
the time.
* Having same-sex intercourse -
http://en.wikipedia.org/wiki/Homosexuality[homosexuality].

For either a man or a woman.

Whether someone will do all that or less is ultimately up to him or her,
but it shouldn’t make you think less of them.

The necessary conditions for that are:

[arabic]
. That they are done in consent.
. That one is 100% honest about their intentions (don’t lie or play
games or do ``Pick up art'' or whatever).

=== Points

==== Tweet #1

«A woman is a lady even if she is or was a porn actress or a prostitute
. Treat her with respect, be honest to her - be a gentleman» —
https://twitter.com/shlomif/status/478025441983213569

Likewise , with ``A woman is a lady'' → ``A man is a gentleman''.

==== About the August 2014 Celebrity Photo Leak

https://www.youtube.com/watch?v=Ake-e4dIVA8&google_comment_id=z13ssjmrkofzfnrae04cfrrzczisvxa4gc4[Comment
on Dave Days’ ``Shake it Off'' parody]

____
I know Jennifer probably feels very badly about her privacy being
violated now due to
https://en.wikipedia.org/wiki/August_2014_celebrity_photo_leaks . I
would feel the same if someone published some of my private E-mails,
even if they are not sexualised. Invading one’s privacy is always bad.

That put aside, here’s some forward looking advice:

{empty}1. Sulk a little without feeling bad about feeling bad (see
http://simpsons.wikia.com/wiki/Moaning_Lisa ). If you feel OK about
feeling bad, you’ll already feel better.

{empty}2. Realise that any sexualised activity, including starring in a
porn film (``XXXX…'' to infinity) or selling sexual services for money
(= prostitution), is neither wrong nor ever disrespectful . A woman or a
man who do some of that are still a lady or a gentleman and should be
respected, loved, and trusted (see
https://en.wikipedia.org/wiki/User:Shlomif/Saladin_Style#Trust_and_Respect
) and are no less of a role model. If any one did all that (including my
close family) I won’t think one iota less of them.

{empty}3. Tell the media that you think that #2 is right, and enjoy the
publicity ( https://duckduckgo.com/?q=all%20publicity%20good%20publicity
- All Publicity is Good Publicity ).

{empty}4. Be proud, stay cool and smashing and awesome, and realise that
there are many people who will love you no matter what.

'''''

Finally, I invite Jennifer (or whoever wishes to come) to attend the
upcoming https://en.wikipedia.org/wiki/ICon_festival in Tel Aviv in
http://en.wikipedia.org/wiki/Sukkot and if she wants, she can contact me
(I have contact info on my home page) and I’ll buy her a drink or a
meal. I know a very good pizza place close to the con’s location, and I
want to see how much pizza she can eat there on my expense. ☺

♥♥♥♥ and XOXO.
____

==== Being a slut

....
<adsc>  millerti: i don't think that there is a human tendency towards monogamy
<rindolf>   pyon: well, words changed in meaning using social activism,
<adsc>  quite the contrary, actually
<OnlyForF1> there is a human tendency towards screwing everything that moves
<rindolf>   Well, I don't think couples own each other's love life or sex life.
<rindolf>   They just shaer them..
<pyon>  OnlyForF1: I would not call it a "human tendency".
<OnlyForF1> animal*
<pyon>  OnlyForF1: We certainly have animal instincts. But, unlike other animals, we can put ourselves above them.
<millerti>  <http://www.newscientist.com/article/dn14641-monogamy-gene-found-in-people.html#.U7vfsxY_1PY>
<OnlyForF1> We can, only because of societal pressure
<pyon>  millerti: If there is a monogamy gene, it must be very weak in me.
<millerti>  pyon: Like I say, you can do what you want.  It doesn’t really affect me.
           However, I have an opinion based on reasoning, not some ancient dogma.
           Monogamy reduces the spread of STDs.
<millerti>  Another interesting article:  <http://www.ncbi.nlm.nih.gov/books/NBK97287/>
<rindolf>   OnlyForF1: I think both men and women appreciate intimacy.
<adsc>  millerti: well, there are good modern tools to prevent the spreading of STDs without monogamy
<rindolf>   Because you need to spend some time with your S.O.
<millerti>  I even more strongly suggest monogamy to gay men, because of the greater ease with which they can share STDs.
<pyon>  millerti: Far more important than being monogamous is carefully picking who you fuck with.
<millerti>  But in any case, condoms are a must.
<millerti>  pyon: Well, you’re right about that.
<rindolf>   njcomsec: BTW, Miranda Kerr is very hot/cute too and she's married to Orlando Bloom and mothered his child,
<adsc>  also, you can test for STDs before you "engage"
<OnlyForF1> They've separated rindolf
<millerti>  Think of monogamy as a preventative measure.  It affects the statistics in a good way.
<rindolf>   OnlyForF1: oh, that sucks.
<OnlyForF1> She did an interview and she talks about how much sex she has
<rindolf>   OnlyForF1: hope they can get over it.
<pyon>  rindolf: Why would anyone besides their family and friends even care?
<rindolf>   OnlyForF1: many women would kill to be married to Orlando Bloom.
<rindolf>   pyon: I just know them.
<OnlyForF1> Many more men would kill to sleep with Kerr.
<Rainb> I wouldn't kill for a celebrity, but hey, that's just me.
....

Retrospectively I (= rindolf) can say that Kerr’s behaviour is a bold
attempt to dispel the belief that women who have sex with many men
(often referred to as ``sluts'' or ``bimbos'') are not being respectful,
and I now support her separation after learning that
https://plus.google.com/+ShlomiFish/posts/EdHs8tEKYmk[Orland Bloom has
been careless] and got himself badly injured several times which is
indicative of a careless character.

===== Excerpt from ``Buffy: A Few Good Slayers''

____
*Willow:* So, do you think I should get a dog?

*Buffy:* Oh, my friend, Rachel, that software developer chick who moved
here, told me that ever since she bought a dog, she made so many friends
and lots of guys showed interest in her, and she’s been telling me about
her exploits with them endlessly.

*Willow:* So she has become a *slut*? So cool!

*Faith:* Hey! ``Slut'' is such a 90s term. The new name for that is
``polyamorous''!

*Buffy:* Which just rolls off the tongue.
____

==== Facebook Post by Shlomi Fish About Socialising with an ~11 y.o Girl

https://www.facebook.com/shlomi.fish/posts/10152215145266981[Facebook
Post]

____
I went on a trip to England, especially for the Nine Worlds GeekFest﻿
con (but continued later on in the Peak District and in Cambridge) and
want to share various anecdotes for it. Here’s the first one:

On the convention, I saw a young girl (about 10 or 11 y.o) cosplaying as
Hermione from the Harry Potter films. Now, she had dirty blonde hair as
opposed to Emma Watson﻿’s original black brownish hair in the films, but
was still quite similar to Hermione. She visited the con along with her
parents, and brother, and I decided to give them these things:

{empty}1. A blue pallet/blue token for good cosplaying. There was a
competition for it later.

{empty}2. A ten-sided die:
https://en.wikipedia.org/wiki/Pentagonal_trapezohedron - which I give to
many people as a token of appreciation because for various reasons I
find the 1d10 to be my amulet of power so-to-speak. (I buy such dice on
stock).

{empty}3. My new business card (
http://www.shlomifish.org/Files/files/images/business-card-without-frame.png
) with my contact details.

{empty}4. I also told them about some of my Harry Potter / Emma Watson
fan fiction, such as
http://www.shlomifish.org/humour/bits/Emma-Watson-applying-for-a-software-dev-job/
or http://www.shlomifish.org/humour/Muppets-Show-TNI/Harry-Potter.html
and they seemed interested to learn.

{empty}5. Her family and I befriended each other.

{empty}6. I saw that girl again, still wearing the costume, in the last
day of the conference and she asked me if I Was going to come next year,
and I told her that I hope to go there (and I do).

'''''

Now for something a little less pleasant: when I told some people on
Freenode IRC about it, someone kept insisting that I was a pervert, just
because I’m 1977-born and 37 years old. I didn’t touch that girl, and
even if I were sexually attracted to her, it’s all right to have such
minor feelings as long as you don’t let them go out of hand. You are
allowed to feel anything, including a desire for mayhem and murder -
it’s just acting based on that emotion that may be questionable.

There is no reason why adults close to 40 (mid-life crisis, yeah
baby!!!) and younger children cannot befriend each other, so please
don’t accuse me of being a pervert, just because I am: 1. Young at
heart. 2. Enjoy the company of good, geeky, people of all ages and all
other parameters for their shapes and sizes:
https://en.wikipedia.org/wiki/One_Fish_Two_Fish_Red_Fish_Blue_Fish .

'''''

A happy (un)?birthday to all!
____

==== ``You feature sexy women and girls in your works. Are you a pervert?''

(From
http://www.shlomifish.org/meta/FAQ/#featuring_sexy_women_and_girls[Shlomi
Fish’s FAQ].)

____
Well, I don’t know about you, but I feel that a man who is attracted to
women displaying sexiness, strength, competence, etc. - however
interpreted - has a healthy https://en.wikipedia.org/wiki/Libido[libido
(or ``sex drive'')] rather than is a pervert, whose sexual preferences
prevent him from functioning.

Furthermore, just because I write about stuff like that, does not mean I
do not have enough self-control, or that I have sex with, sexually
assault, or sexually harass everything that moves.

It is also obvious from my stories, that I do not wish any harm on the
heroes (or often even the villains) of my stories: in general, they do
not get killed, or raped, or even become pregnant without intending to.
While they have some hardships, they end up performing some amazing
achievements of competence, and all that while not having any
supernatural powers.

'''''

Now regarding their *age*: yes, I’m aware that some of them are
underage, and only in high school. But it may seem farfetched, but I
think that underage girls and boys can still be competent, both in their
tangible endeavours, but also in their sexual/romantic orientation. Back
at the time, http://en.wikipedia.org/wiki/Macaulay_Culkin[Macaulay
Culkin], who was the ``alpha male'' of a large part of the 1990s
(despite his youth), raised a few eyebrows, when marrying at the age of
18 shortly after high school graduation. However, I recently heard of a
Jewish couple of a guy and a girl who are 15 now, and as scary as it
sounds, it didn’t seem too horrid of a thought. Some people
http://www.youtube.com/watch?v=lQALLGsn-Fk[learn faster than others].

Just another note about Culkin: some people also criticised him for
possessing Marijuana and for its use, but many young and not-so-young
people I talked with have had a history of Marijuana use, or even
Marijuana addiction, so I do not hold it against him. See my
https://www.shlomifish.org/philosophy/politics/drug-legalisation/[The Case for
Drug Legalisation] for why Marijuana, and all other illegal narcotics,
should be made legal globally.
____

== 99 Problems

=== Original

* https://en.wikipedia.org/wiki/99_Problems[``99 Problems'' by Jay-Z] -
``If you’re having girl problems, I feel bad for you son, I got 99
problems but a bitch ain’t one''. Chorus taken from
https://en.wikipedia.org/wiki/Home_Invasion_%28album%29[a single by
Ice-T].
** https://www.youtube.com/watch?v=LloIp0HMJjc[Pop cover by Hugo] - with
a different melody and lyrics.

=== xkcd: Perl Problems

http://xkcd.com/1171/[xkcd: Perl problems]:

____
Two figures stand facing each other. One is wearing sunglasses.

Figure with sunglasses: If you’re havin’ Perl problems I feel bad for
you, son-

Figure with sunglasses: I got 99 problems,

Figure with sunglasses: so I used regular expressions.

Figure with sunglasses: Now I have 100 problems.
____

=== Problem (Ariana Grande song)

http://en.wikipedia.org/wiki/Problem_%28Ariana_Grande_song%29[wikipedia:Problem
(Ariana Grande song)]

* ``Got one less problem without you.''
* ``I’ve got 99 problems but you won’t be one.''
* https://www.youtube.com/watch?v=4kTUwAreg7c[Cover by Tiffany Alvord
and Alex G]
* https://www.youtube.com/watch?v=z_pkqLb3kq0[Cover by Cimorelli]
* https://www.youtube.com/watch?v=4Z9b2HiW_L8[Cover by Pentatonix]

==== The Key of Awesome Parody

https://www.youtube.com/watch?v=-koXQqD0p5s[Ariana Grande - Problem ft.
Iggy Azalea PARODY! Key Of Awesome #87]

«Well, it’s one less paycheck.»

____
How much wood would a woodchuck chuck if a woodchuck could chuck wood,
I’ve got 99 verses, but they ain’t that good.
____

==== Bart Baker Parody

https://www.youtube.com/watch?v=4_qKaiGqALo[Bart Baker Parody]

=== Summerschool at the NSA

* http://www.shlomifish.org/humour/Summerschool-at-the-NSA/ongoing-text.html#getting_clearance__at_the_guards[Summer
Glau and the two guarding soldiers about problem arithemtics]:

____
SGlau: So? How’s life?

Andrew: It sucks.

Daniel: Yes, it sucks.

SGlau: Ninety-nine problems, eh?

Daniel: And a bitch ain’t one? yes!

Andrew: Actually, I have a hundred problems.

SGlau: Ah, a significant other?

Andrew: Yes, and me being a soldier here makes her really bitchy.

SGlau: Nice, what is her name?

Andrew: Her name is Felicia, Ma’am.

SGlau: Nice name.

Andrew: Yes, nice name.

SGlau: I suppose serving here at the NSA is also one of your problems?

Daniel: Hey, this place is at least ninety of my problems.

Andrew: I wish it was less than that for me too. I was actually happier
in Afghanistan.

.

.

.

SGlau: Yes, you are right. I’m here to kick some serious NSA ass (not in
the physical sense, of course), and make sure you two have ten and nine
problems respectively.

.

.

.

Daniel: Hey! How about one of us escorting you?

Andrew: Yeah, but who?

Daniel: Andrew, how about you this time?

Andrew: Heh — sure! If only to make my girlfriend jealous.

SGlau: And more bitchy!
____

=== Shlomi Fish’s Chuck Norris/etc. facts

* http://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-fact-chuck-86[``Chuck
Norris has 99 problems including a bitch.'']
* http://www.shlomifish.org/humour/fortunes/show.cgi?id=shlomif-fact-sglau-13[``Chuck
Norris has 99 problems including a bitch. Summer Glau has exactly 98
problems.'']

=== #perl-cats ``In Soviet Russia'' Fortune

http://www.shlomifish.org/humour/fortunes/show.cgi?id=sharp-perl-cats-cats-in-soviet-russia[``I’ve
got 99 problems but kent\n ain’t one.'']

=== From IRC

____
*rindolf*: Yes, I’m single - I’ve got 99 problems but a bitch ain’t one.
____

____
*rindolf*: And yes, I realise that the guy who said that (Jay-Z) now has
a 100th problem (a bitch) and a 101st problem (a child).
____

(See http://beyonce.wikia.com/wiki/Jay_Z[``Jay-Z entry'' from the
Beyoncé wikipedia].)

(*P.S*: and now he reportedly has even more problems: a reported affair
with his wife’s sister, and a rumored divorce).

(*PPS*: the couple appears to https://beyoncepedia.fandom.com/wiki/Jay-Z[have
remained together]. Good for them.)

== Honest pick-up art

=== Fresh Prince of Bel-Air: Jazz as a pickup artist:

* https://www.youtube.com/watch?v=KcD7hvH0Wk8[YouTube video]
* https://www.reddit.com/r/FreshPrince/comments/d5n1n0/jazz_as_a_pickup_artist/[/r/FreshPrince discussion]

=== DAILY GRADVICE

* https://www.youtube.com/watch?v=21uXcvD5lPs[DAILY GRADVICE] - "I want you to sail your dick ship into my lady port"

== Beauty and the Geek

[quote, @shlomif, https://twitter.com/shlomif/status/1188008763363606529]
___
Shlomi Fish
@shlomif
1st time I was offered to be in beauty and the geek in Israel I voiced this rebuttal: https://shlomif.livejournal.com/63847.html . I was wrong to criticise reality show contestants - https://shlomifish.org/humour.html#pbride_philosophers but nowadays almost all attractive girls are not only attracted to geeks but are quite geeky (= scientifically or technologically or craft/art wise) themselves.
___

